steps:
  # 1. Instala as dependências do Python de forma global no contêiner.
  - name: 'python:3.11'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt'] # <-- A flag '--user' foi removida.

  # 2. O passo de deploy está correto.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'jitakyoapp'
      - '--source'
      - '.'
      - '--region'
      - 'southamerica-east1'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'

options:
  logging: CLOUD_LOGGING_ONLY

