options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'backend' 
  args: [
    'build', 
    '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/jitakyoapp-image:$SHORT_SHA', 
    '.'
  ]

# Passo 2: Envia a imagem para o Artifact Registry do Google
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/jitakyoapp-image:$SHORT_SHA']

# Passo 3: Faz o deploy da nova imagem no Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', 'jitakyoapp',
    '--image', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/jitakyoapp-image:$SHORT_SHA',
    '--region', 'southamerica-east1',
    '--platform', 'managed',
    '--allow-unauthenticated'
  ]

# Informa ao Cloud Build qual imagem foi criada para referência
images:
- 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/jitakyoapp-image:$SHORT_SHA'