steps:
  # 1. Instala as dependências do Python
  - name: 'python:3.11'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt', '--user']

  # 2. Executa o deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'jitakyoapp' # <-- O nome do seu serviço no Cloud Run
      - '--source'
      - '.'
      - '--region'
      - 'southamerica-east1' # <-- A região do seu serviço
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'
options:
  logging: CLOUD_LOGGING_ONLY