# .github/workflows/deploy-frontend.yml

name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # <-- ESTA LINHA FOI ALTERADA DE '18' PARA '20'

      - name: Install Frontend Dependencies
        run: cd frontend && npm ci

      - name: Create .env file
        run: |
          cd frontend
          echo VITE_FIREBASE_API_KEY="${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo VITE_FIREBASE_AUTH_DOMAIN="${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo VITE_FIREBASE_PROJECT_ID="${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo VITE_FIREBASE_STORAGE_BUCKET="${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo VITE_FIREBASE_MESSAGING_SENDER_ID="${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo VITE_FIREBASE_APP_ID="${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env
          echo VITE_FIREBASE_MEASUREMENT_ID="${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> .env

      - name: Build Frontend Application (Admin Panel)
        run: cd frontend && npm run build

      - name: Deploy to Firebase Hosting (Admin + Aluno)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JITAKYOAPP }}'
          projectId: jitakyoapp

